version: '3'
services:
  postgres-db:
    image: docker.io/library/postgres:15.2-alpine
    container_name: postgres-db
    env_file:
      - ./config/default-container.env
      - ./config/postgres-db.env
    ports:
      - 5432:5432
    volumes:
      - /home/${USER}/postgres/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/locatime:ro
    networks:
      - postgres-net
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "baeldung:1:1"
    networks:
      - kafka-net
networks:
  postgres-net:
    driver: bridge
  kafka-net:
    driver: bridge
