server:
  port: 9100
spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:inventory-db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  cloud:
    function:
      definition: processor
    stream:
      default:
        producer:
          useNativeEncoding: true
      bindings:
        processor-in-0:
          destination: order-events
          group: inventory-group
        processor-out-0:
          destination: inventory-events
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9093}
          consumer-properties:
            "value.deserializer": org.springframework.kafka.support.serializer.JsonDeserializer
            "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
            "auto.offset.reset": "earliest"
            "spring.json.trusted.packages": "com.ldsk.common.events.*"
          producer-properties:
            "value.serializer": org.springframework.kafka.support.serializer.JsonSerializer
            "key.serializer": org.apache.kafka.common.serialization.StringSerializer