server:
  port: 8080
spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:order-db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  cloud:
    function:
      definition: orderEventProducer;paymentProcessor;inventoryProcessor;shippingProcessor
    stream:
      default:
        producer:
          useNativeEncoding: true
      bindings:
        order-events-channel:
          destination: order-events
        paymentProcessor-in-0:
          destination: payment-events
          group: order-service-group
#        paymentProcessor-out-0:
#          destination: order-events
        inventoryProcessor-in-0:
          destination: inventory-events
          group: order-service-group
#        inventoryProcessor-out-0:
#          destination: order-events
        shippingProcessor-in-0:
          destination: shipping-events
          group: order-service-group
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9093}
          consumer-properties:
            "value.deserializer": org.springframework.kafka.support.serializer.JsonDeserializer
            "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
            "auto.offset.reset": "earliest"
            "spring.json.trusted.packages": "com.ldsk.common.events.*"
          producer-properties:
            "value.serializer": org.springframework.kafka.support.serializer.JsonSerializer
            "key.serializer": org.apache.kafka.common.serialization.StringSerializer